name: GitHub Actions Demo
run-name: testy testy testy
on:
  schedule:
    - cron: "26 * * * *"
jobs:
  incrementally-build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          node buildAndRelease.js
