name: GitHub Actions Demo
run-name: testy testy schedule testy
on:
  schedule:
    - cron: "32 * * * *"
jobs:
  incrementally-build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        name: state.json
      - run: |
          node buildAndRelease.js
      - uses: actions/upload-artifact@v4
        name: state.json
